<?php

define('ISLANDORA_GENERIC_SP_MODS_FORM_NAME', 'ISLANDORA GENERIC MODS FORM');

function islandora_generic_sp_required_fedora_objects() {
  $module_path = drupal_get_path('module', 'islandora_generic_sp');
  $form_xml = file_get_contents("$module_path/xml/mods_generic.xml");
  solution_pack_add_form($form_name, $form_xml);
  solution_pack_add_form_association('islandora:sp_generic', $form_name);
  // Put the form in the database
  module_load_include('inc', 'xml_form_builder', 'XMLFormDatabase');
  if (!XMLFormDatabase::Exists(ISLANDORA_GENERIC_SP_MODS_FORM_NAME)) {
    $definition = new DOMDocument();
    $definition->load($module_path . '/xml/mods_generic.xml');
    XMLFormDatabase::Create(ISLANDORA_GENERIC_SP_MODS_FORM_NAME, $definition);
  }
  // Associates the form with the content model
  $result = db_result(db_query('Select content_model from {islandora_content_model_forms} where  content_model = "%s" and form_name = "%s"', 'islandora:sp_generic', 'Islandora Generic Collection'));
  if (!$result) {
    $object = new stdClass();
    $object->content_model = 'islandora:sp_generic';
    $object->form_name = 'Islandora Generic MODS Form';
    $object->dsid = 'MODS';
    $object->title_field = "['titleInfo']['title']";
    $object->transform = 'mods_to_dc.xsl';
    $result = drupal_write_record('islandora_content_model_forms', $object);
  }
  return  array(
        'islandora_generic_sp' => array(
          'module' => 'islandora_generic_sp',
          'title' => 'Islandora Generic Solution Pack',
          'objects' => array(
              array(
              'pid' => 'islandora:sp_generic',
              'label' => 'Islandora Generic content model',
              'dsid' => 'ISLANDORACM',
              'datastream_file' => "$module_path/xml/GENERIC_SP_CMODEL.xml",
              'cmodel' => 'fedora-system:ContentModel-3.0',
              ),
              array(
              'pid' => 'islandora:sp_generic_collection',
              'label' => 'Islandora GENERIC Collection',
              'cmodel' => 'islandora:collectionCModel',
              'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
              'datastreams' => array(
                      array(
                      'dsid' => 'TN',
                      'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
                      'mimetype' => 'image/png',
                      ),
                      array(
                      'dsid' => 'COLLECTION_POLICY',
                      'datastream_file' => "$module_path/xml/GENERIC-COLLECTION_POLICY.xml",
                      ),
                                    ),
                ),
                          ),
                                    ),
              );
}
